using System.Collections.Generic;
using SwiftMap.SourceGenerator.Models;

namespace SwiftMap.SourceGenerator.Emit;

internal static class MappingBodyEmitter
{
    public static string Emit(MapperClassModel model)
    {
        var w = new SourceWriter();

        w.AppendLine("// <auto-generated/>");
        w.AppendLine("// SwiftMap.SourceGenerator — do not edit manually.");
        w.AppendLine("#nullable enable");
        w.AppendLine();

        bool hasNs = !string.IsNullOrEmpty(model.Namespace);
        if (hasNs)
        {
            w.AppendLine($"namespace {model.Namespace}");
            w.OpenBrace();
        }

        w.AppendLine($"partial class {model.ClassName}");
        w.OpenBrace();

        for (int mi = 0; mi < model.Methods.Count; mi++)
        {
            if (mi > 0) w.AppendLine();
            EmitMethod(w, model.Methods[mi]);
        }

        w.CloseBrace(); // partial class

        if (hasNs)
            w.CloseBrace(); // namespace

        return w.ToString();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Method body
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitMethod(SourceWriter w, MappingMethodModel m)
    {
        w.AppendLine($"public partial {m.DestFqn} {m.MethodName}({m.SourceFqn} {m.ParamName})");
        w.OpenBrace();

        // Hoist collection variables before the return statement
        int collectionIdx = 0;
        foreach (var prop in m.Properties)
            if (prop.Kind == MappingKind.Collection)
                EmitCollectionHoist(w, prop, m.ParamName, ref collectionIdx);

        if (m.DestIsRecord)
            EmitRecordReturn(w, m);
        else
            EmitObjectInitReturn(w, m, collectionIdx);

        w.CloseBrace();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Record: return new Dest(param: value, ...)
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitRecordReturn(SourceWriter w, MappingMethodModel m)
    {
        w.AppendLine($"return new {m.DestFqn}(");
        w.Indent();
        for (int i = 0; i < m.Properties.Count; i++)
        {
            var prop = m.Properties[i];
            string comma = i < m.Properties.Count - 1 ? "," : "";
            string val = ScalarExpression(prop, m.ParamName);
            // Use actual constructor parameter name if known, otherwise camelCase fallback
            string paramName = prop.CtorParamName
                ?? (char.ToLowerInvariant(prop.DestName[0]) + prop.DestName.Substring(1));
            w.AppendLine($"{paramName}: {val}{comma}");
        }
        w.Dedent();
        w.AppendLine(");");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Object initializer: return new Dest { Prop = val, ... }
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitObjectInitReturn(SourceWriter w, MappingMethodModel m, int collectionVarCount)
    {
        w.AppendLine($"return new {m.DestFqn}");
        w.OpenBrace();

        int ci = 0; // collection variable index tracker
        for (int i = 0; i < m.Properties.Count; i++)
        {
            var prop = m.Properties[i];
            string comma = i < m.Properties.Count - 1 ? "," : "";

            switch (prop.Kind)
            {
                case MappingKind.Collection:
                    // Reference the hoisted variable
                    w.AppendLine($"{prop.DestName} = __col{ci++}{comma}");
                    break;
                case MappingKind.Nested:
                    EmitNestedInline(w, prop, m.ParamName, comma);
                    break;
                default:
                    w.AppendLine($"{prop.DestName} = {ScalarExpression(prop, m.ParamName)}{comma}");
                    break;
            }
        }

        w.CloseBrace(semicolon: true);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Nested object inline (is-pattern null check)
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitNestedInline(SourceWriter w, MappedPropertyModel prop, string paramName, string comma)
    {
        string srcExpr = prop.SourceExpression;
        string tmpVar = $"__n{prop.DestName}";

        if (prop.SourceIsNullable || !prop.DestIsNullable)
        {
            // Null-safe: source.Addr is { } __nAddr ? new Dest { ... } : null,
            w.AppendLine($"{prop.DestName} = {srcExpr} is {{ }} {tmpVar}");
            w.Indent();
            if (prop.NestedIsRecord)
                EmitNestedRecordInit(w, prop, tmpVar, $"{comma}");
            else
                EmitNestedObjectInit(w, prop, tmpVar, $": null{comma}");
            w.Dedent();
        }
        else
        {
            // Source cannot be null
            if (prop.NestedIsRecord)
            {
                w.AppendLine($"{prop.DestName} = new {prop.ElementDestFqn}(");
                w.Indent();
                EmitNestedCtorArgs(w, prop, srcExpr);
                w.Dedent();
                w.AppendLine($"){comma}");
            }
            else
            {
                w.AppendLine($"{prop.DestName} = new {prop.ElementDestFqn}");
                w.OpenBrace();
                EmitNestedPropertyLines(w, prop, srcExpr);
                w.CloseBrace(semicolon: false);
                if (!string.IsNullOrEmpty(comma)) w.AppendLine(comma);
            }
        }
    }

    private static void EmitNestedObjectInit(SourceWriter w, MappedPropertyModel prop, string tmpVar, string trailer)
    {
        w.AppendLine($"? new {prop.ElementDestFqn}");
        w.OpenBrace();
        EmitNestedPropertyLines(w, prop, tmpVar);
        w.CloseBrace(semicolon: false);
        w.AppendLine(trailer);
    }

    private static void EmitNestedRecordInit(SourceWriter w, MappedPropertyModel prop, string tmpVar, string trailer)
    {
        w.AppendLine($"? new {prop.ElementDestFqn}(");
        w.Indent();
        EmitNestedCtorArgs(w, prop, tmpVar);
        w.Dedent();
        w.AppendLine($"): null{trailer}");
    }

    private static void EmitNestedPropertyLines(SourceWriter w, MappedPropertyModel prop, string srcExpr)
    {
        var nested = prop.NestedProperties;
        if (nested == null) return;
        for (int i = 0; i < nested.Count; i++)
        {
            var np = nested[i];
            string comma = i < nested.Count - 1 ? "," : "";
            string val = ScalarExpressionRaw(np, srcExpr);
            w.AppendLine($"{np.DestName} = {val}{comma}");
        }
    }

    private static void EmitNestedCtorArgs(SourceWriter w, MappedPropertyModel prop, string srcExpr)
    {
        var nested = prop.NestedProperties;
        if (nested == null) return;
        for (int i = 0; i < nested.Count; i++)
        {
            var np = nested[i];
            string comma = i < nested.Count - 1 ? "," : "";
            string paramName = np.CtorParamName
                ?? (char.ToLowerInvariant(np.DestName[0]) + np.DestName.Substring(1));
            string val = ScalarExpressionRaw(np, srcExpr);
            w.AppendLine($"{paramName}: {val}{comma}");
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Collection hoisting
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitCollectionHoist(SourceWriter w, MappedPropertyModel prop, string paramName, ref int idx)
    {
        string srcVar = $"__src{idx}";
        string dstVar = $"__col{idx}";
        string iVar = $"__i{idx}";
        idx++;

        w.AppendLine($"var {srcVar} = {prop.SourceExpression};");

        bool hasNested = prop.NestedProperties != null && prop.NestedProperties.Count > 0;
        string elemDst = prop.ElementDestFqn ?? "object";

        if (hasNested)
        {
            // Use array allocation + for-loop with object initializer
            w.AppendLine($"var {dstVar} = new {elemDst}[{srcVar}.Count];");
            w.AppendLine($"for (int {iVar} = 0; {iVar} < {srcVar}.Count; {iVar}++)");
            w.OpenBrace();

            if (prop.NestedIsRecord)
            {
                w.AppendLine($"{dstVar}[{iVar}] = new {elemDst}(");
                w.Indent();
                var nested = prop.NestedProperties!;
                for (int pi = 0; pi < nested.Count; pi++)
                {
                    var np = nested[pi];
                    string comma = pi < nested.Count - 1 ? "," : "";
                    string pname = np.CtorParamName
                        ?? (char.ToLowerInvariant(np.DestName[0]) + np.DestName.Substring(1));
                    // Adjust the source accessor to use the indexed element
                    string srcAccess = $"{srcVar}[{iVar}].{np.SourceExpression.Substring("__item.".Length)}";
                    w.AppendLine($"{pname}: {srcAccess}{comma}");
                }
                w.Dedent();
                w.AppendLine(");");
            }
            else
            {
                w.AppendLine($"{dstVar}[{iVar}] = new {elemDst}");
                w.OpenBrace();
                var nested = prop.NestedProperties!;
                for (int pi = 0; pi < nested.Count; pi++)
                {
                    var np = nested[pi];
                    string comma = pi < nested.Count - 1 ? "," : "";
                    string srcAccess = $"{srcVar}[{iVar}].{np.SourceExpression.Substring("__item.".Length)}";
                    w.AppendLine($"{np.DestName} = {srcAccess}{comma}");
                }
                w.CloseBrace(semicolon: true);
            }

            w.CloseBrace();
        }
        else
        {
            // Primitive element — direct copy via for-loop
            string elemSrc = prop.ElementSourceFqn ?? elemDst;
            w.AppendLine($"var {dstVar} = new {elemDst}[{srcVar}.Count];");
            w.AppendLine($"for (int {iVar} = 0; {iVar} < {srcVar}.Count; {iVar}++)");
            w.Indent();
            w.AppendLine($"{dstVar}[{iVar}] = ({elemDst}){srcVar}[{iVar}];");
            w.Dedent();
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Scalar expression generation
    // ─────────────────────────────────────────────────────────────────────────

    private static string ScalarExpression(MappedPropertyModel prop, string paramName)
        => ScalarExpressionRaw(prop, paramName);

    private static string ScalarExpressionRaw(MappedPropertyModel prop, string srcPrefix)
    {
        // Recalculate the source accessor using the correct prefix
        int dotPos = prop.SourceExpression.IndexOf('.');
        string srcAccess = dotPos >= 0
            ? $"{srcPrefix}.{prop.SourceExpression.Substring(dotPos + 1)}"
            : prop.SourceExpression;

        return prop.Kind switch
        {
            MappingKind.NullableUnwrap => $"({prop.DestTypeFqn}){srcAccess}",
            MappingKind.Enum when prop.EnumToString => $"{srcAccess}.ToString()",
            MappingKind.Enum when prop.StringToEnum
                => $"({prop.DestTypeFqn})global::System.Enum.Parse(typeof({prop.DestTypeFqn}), {srcAccess}, true)",
            MappingKind.Enum when prop.EnumDifferentType => $"({prop.DestTypeFqn})(int){srcAccess}",
            _ => srcAccess,
        };
    }
}
